# Generated by Django 3.1a1 on 2020-05-16 05:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='match',
            name='username',
            field=models.CharField(max_length=20, verbose_name=django.contrib.auth.models.User),
        ),
    ]
